packageExtensions:
  "@vitejs/plugin-vue@*":
    dependencies:
      "supports-color": "*"
  "@vue/test-utils@*":
    dependencies:
      "@vue/compiler-dom": "*"
      "supports-color": "*"
  "debug@*":
    dependencies:
      "supports-color": "*"
  "vite@*":
    dependencies:
      "supports-color": "*"
