packageExtensions:
  "debug@*":
  "@vitejs/plugin-vue@*":
  "@vue/test-utils@*":
  "vite@*":
    dependencies:
      "supports-color": "*"
  "@vue/test-utils@*":
    dependencies:
      "@vue/compiler-dom": "*"
